### ISSUE TITLE
`ValueError` when running `make debug-server` on an app page

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#639]
I get [this error](https://gist.github.com/MaxGhenis/f5c70021175e4fdac4ed9573ffe64203) when loading the US or UK app locally. I tried `make install` and `make build-server`, and also with or without the synthetic flag, still get the same thing.

**Comment by nikhilwoodruff** [comment]
OK, so the cause of this is that when we started using baseline values of benefits for logic (e.g. for takeup), we store these in OpenFisca-UK. But the Enhanced FRS was now a different size than the original FRS due to cloning processes, and the synthetic FRS hadn't been updated, so the microsim fails to load baseline variables for the enhanced FRS because of this different size.

The fix should be to re-download the synthetic dataset (or the enhanced FRS) with `openfisca-uk-data synth_frs download 2019`. Does that work?

**Comment by MaxGhenis** [comment]
Some combination of that command and updating my local clones of `openfisca-uk` and `openfisca-uk-data` worked. That it downloaded in the `make debug-server` script (below) suggests it was the package versions. Might that not have worked with `make install` because of conflicts between the PyPI and local (`pip install -e .`) versions?
```shell
(base) maxghenis@Maxs-MacBook-Pro policyengine % UK_SYNTHETIC=1 make debug-server
POLICYENGINE_DEBUG=1 FLASK_APP=policyengine/server.py FLASK_DEBUG=1 flask run
 * Serving Flask app "policyengine/server.py" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 305-735-008
INFO:PolicyEngine:Initialising server.
WARNING:root:Using the synthetic FRS.
INFO:root:2019 not found in dataset synth_frs years, downloading.
INFO:PolicyEngine:Initialising server.
WARNING:root:Using the synthetic FRS.
INFO:root:2019 not found in dataset synth_frs years, downloading.
100%|██████████████████████████| 117M/117M [00:06<00:00, 17.2MiB/s]
100%|██████████████████████████| 117M/117M [00:08<00:00, 13.4MiB/s]
INFO:PolicyEngine:Initialisation complete.
```
