### ISSUE TITLE
State code doesn't save visually in household page (still saved for simulation)

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#777]
To repro:
1. Go to https://policyengine.org/us/household
2. Change the state from CA to MA in the Location menu
3. Go to another menu
4. Return to the Location menu

Expected: shows MA
Result: shows CA

It still shows MA results, so this is just a UI bug.

**Comment by MaxGhenis** [comment]
Now I think it's actually not just a UI bug. Selecting MD and entering ~$100k of earnings doesn't show state income taxes:
<img width="911" alt="image" src="https://user-images.githubusercontent.com/6076111/180128008-05ac361a-0b41-406c-a930-680bfbe36751.png">

**Comment by nikhilwoodruff** [comment]
Just checked - I think it is a UI bug: the reason it doesn't show State income taxes (but here Taxes > Payroll tax + Federal income tax) is because we don't show the State income tax variable, but instead the actual MA income tax variable (so that users can expand it and see the breakdown components specific to their State).
