### ISSUE TITLE
Policy cart needs more space

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine#784]
For longer policy parameters, they fill up the cart and prevent users from activating pagination
<img width="363" alt="image" src="https://user-images.githubusercontent.com/6076111/175788022-84c96178-e1aa-49c8-87f9-33133b51ad54.png">

**Comment by Felix-Cadiz** [comment]
With previously committed updates, this issue seems to be fixed.

As for styling, **would we want the pagination to be centered?**

![Screen Shot 2022-08-24 at 9 55 04 AM](https://user-images.githubusercontent.com/88756231/186477842-d063e19e-396e-44c6-8358-b00de5b7161a.png)
![Screen Shot 2022-08-24 at 9 55 12 AM](https://user-images.githubusercontent.com/88756231/186477848-d4e2e1ac-1fce-4e29-9263-8597bf0e8bfb.png)

**Comment by MaxGhenis** [comment]
Nice, yes let's center the pagination

**Comment by Felix-Cadiz** [comment]
With centering, we can move in three directions: 

1) Centering the page the user is currently on: 
<img width="309" alt="Screen Shot 2022-08-25 at 12 34 43 PM" src="https://user-images.githubusercontent.com/88756231/186753231-9dbc1da3-9c47-477d-ad23-7232d4cca6e5.png">

2) Centering the pagination as it currently is. Despite it being the in the center, because the "/" is not in the center of the element itself, one side will always have more than the other: 

<img width="363" alt="Screen Shot 2022-08-25 at 12 36 32 PM" src="https://user-images.githubusercontent.com/88756231/186753415-0f8e1ce2-be32-41ef-8967-0d5334c15fc3.png">

3) Change the pagination layout to a different design. This is already built into the package we are pulling from, it's just a different design. With this choice, everything can be easily centered as the icon sizes are equal in size. 

<img width="362" alt="Screen Shot 2022-08-25 at 12 37 14 PM" src="https://user-images.githubusercontent.com/88756231/186754352-41d927cd-b427-45a8-a6a1-d134de0df4c3.png">

**Comment by MaxGhenis** [comment]
Let's go with 3
